AllCops:
  TargetRubyVersion: 2.3

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/*'
    - 'ember-workflows/**/*'
    - 'cookbooks/**/*'
    - 'Vagrantfile'

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/BlockAlignment:
  Enabled: false

Lint/DefEndAlignment:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 231

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 5000

Metrics/CyclomaticComplexity:
  Max: 26

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false
  Max: 120

Metrics/MethodLength:
  Max: 160

Metrics/ModuleLength:
  Max: 1000

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Performance/Count:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ArrayJoin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentIndentation:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/ElseAlignment:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/EmptyLines:
  Enabled: true

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Style/IndentationWidth:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 9

Style/OneLineConditional:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAfterColon:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceBeforeComment:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/Tab:
  Enabled: true
  AutoCorrect: true

Style/TrailingBlankLines:
  Enabled: true
  AutoCorrect: true

Style/TrailingWhitespace:
  Enabled: true
  AutoCorrect: true

Style/UnlessElse:
  Enabled: true

Style/UnneededCapitalW:
  Enabled: false

Style/WordArray:
  MinSize: 3

Style/DoubleNegation:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false
